name: Deployment
on:
  push:
    branches:
      - main
      - dev
env:
  DB_NAME: simple-db
  PORT: 8080
jobs:
  test:
    environment: testing
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: echo "Running Server At ${{ env.PORT }}"
      - name: Output information
        run: echo "${{ env.DB_NAME }}, ${{ env.PASSWORD }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "${{ env.DB_NAME }}"
